### ISSUE TITLE
Unsupported state or unable to authenticate data

### ISSUE THREAD

**Issue by fegauthier** [RunOnFlux/Flux-Shared-DB#8]
Hi!

I tried to deploy Shared DB on Flux, but there is an error when encryption.

You can take a look at the app diabloepgwithdb to see me configurations. I based my configuration for Shared DB on wordpressonflux.

Do you have an idea why I have this error?

Thanks!

```
#Waiting for local DB to boot up...
8Error: Unsupported state or unable to authenticate data
=    at Decipheriv.final (node:internal/crypto/cipher:193:29)
A    at Function.decrypt (/app/ClusterOperator/Security.js:60:57)
@    at Function.getKey (/app/ClusterOperator/Security.js:89:17)
>    at DBClient.init (/app/ClusterOperator/DBClient.js:80:28)
R    at async Object.exports.createClient (/app/ClusterOperator/DBClient.js:193:5)
O    at async Function.ConnectLocalDB (/app/ClusterOperator/Operator.js:596:24)
F    at async Function.initDB (/app/ClusterOperator/Operator.js:607:9)
D    at async Function.init (/app/ClusterOperator/Operator.js:622:5)
>    at async initServer (/app/ClusterOperator/server.js:69:3)
#Waiting for local DB to boot up...
8Error: Unsupported state or unable to authenticate data
=    at Decipheriv.final (node:internal/crypto/cipher:193:29)
A    at Function.decrypt (/app/ClusterOperator/Security.js:60:57)
@    at Function.getKey (/app/ClusterOperator/Security.js:89:17)
>    at DBClient.init (/app/ClusterOperator/DBClient.js:80:28)
R    at async Object.exports.createClient (/app/ClusterOperator/DBClient.js:193:5)
O    at async Function.ConnectLocalDB (/app/ClusterOperator/Operator.js:596:24)
F    at async Function.initDB (/app/ClusterOperator/Operator.js:607:9)
D    at async Function.init (/app/ClusterOperator/Operator.js:622:5)
>    at async initServer (/app/ClusterOperator/server.js:69:3)
#Waiting for local DB to boot up...
8Error: Unsupported state or unable to authenticate data
=    at Decipheriv.final (node:internal/crypto/cipher:193:29)
A    at Function.decrypt (/app/ClusterOperator/Security.js:60:57)
@    at Function.getKey (/app/ClusterOperator/Security.js:89:17)
>    at DBClient.init (/app/ClusterOperator/DBClient.js:80:28)
R    at async Object.exports.createClient (/app/ClusterOperator/DBClient.js:193:5)
O    at async Function.ConnectLocalDB (/app/ClusterOperator/Operator.js:596:24)
F    at async Function.initDB (/app/ClusterOperator/Operator.js:607:9)
D    at async Function.init (/app/ClusterOperator/Operator.js:622:5)
>    at async initServer (/app/ClusterOperator/server.js:69:3)
#Waiting for local DB to boot up...
8Error: Unsupported state or unable to authenticate data
=    at Decipheriv.final (node:internal/crypto/cipher:193:29)
A    at Function.decrypt (/app/ClusterOperator/Security.js:60:57)
@    at Function.getKey (/app/ClusterOperator/Security.js:89:17)
>    at DBClient.init (/app/ClusterOperator/DBClient.js:80:28)
R    at async Object.exports.createClient (/app/ClusterOperator/DBClient.js:193:5)
O    at async Function.ConnectLocalDB (/app/ClusterOperator/Operator.js:596:24)
F    at async Function.initDB (/app/ClusterOperator/Operator.js:607:9)
D    at async Function.init (/app/ClusterOperator/Operator.js:622:5)
>    at async initServer (/app/ClusterOperator/server.js:69:3)
#Waiting for local DB to boot up...
#Waiting for local DB to boot up...
8Error: Unsupported state or unable to authenticate data
=    at Decipheriv.final (node:internal/crypto/cipher:193:29)
A    at Function.decrypt (/app/ClusterOperator/Security.js:60:57)
@    at Function.getKey (/app/ClusterOperator/Security.js:89:17)
>    at DBClient.init (/app/ClusterOperator/DBClient.js:80:28)
R    at async Object.exports.createClient (/app/ClusterOperator/DBClient.js:193:5)
O    at async Function.ConnectLocalDB (/app/ClusterOperator/Operator.js:596:24)
F    at async Function.initDB (/app/ClusterOperator/Operator.js:607:9)
D    at async Function.init (/app/ClusterOperator/Operator.js:622:5)
>    at async initServer (/app/ClusterOperator/server.js:69:3)
8Error: Unsupported state or unable to authenticate data
=    at Decipheriv.final (node:internal/crypto/cipher:193:29)
A    at Function.decrypt (/app/ClusterOperator/Security.js:60:57)
@    at Function.getKey (/app/ClusterOperator/Security.js:89:17)
>    at DBClient.init (/app/ClusterOperator/DBClient.js:80:28)
R    at async Object.exports.createClient (/app/ClusterOperator/DBClient.js:193:5)
O    at async Function.ConnectLocalDB (/app/ClusterOperator/Operator.js:596:24)
F    at async Function.initDB (/app/ClusterOperator/Operator.js:607:9)
D    at async Function.init (/app/ClusterOperator/Operator.js:622:5)
>    at async initServer (/app/ClusterOperator/server.js:69:3)
#Waiting for local DB to boot up...
8Error: Unsupported state or unable to authenticate data
=    at Decipheriv.final (node:internal/crypto/cipher:193:29)
A    at Function.decrypt (/app/ClusterOperator/Security.js:60:57)
@    at Function.getKey (/app/ClusterOperator/Security.js:89:17)
>    at DBClient.init (/app/ClusterOperator/DBClient.js:80:28)
R    at async Object.exports.createClient (/app/ClusterOperator/DBClient.js:193:5)
O    at async Function.ConnectLocalDB (/app/ClusterOperator/Operator.js:596:24)
F    at async Function.initDB (/app/ClusterOperator/Operator.js:607:9)
D    at async Function.init (/app/ClusterOperator/Operator.js:622:5)
>    at async initServer (/app/ClusterOperator/server.js:69:3)
#Waiting for local DB to boot up...
8Error: Unsupported state or unable to authenticate data
=    at Decipheriv.final (node:internal/crypto/cipher:193:29)
A    at Function.decrypt (/app/ClusterOperator/Security.js:60:57)
@    at Function.getKey (/app/ClusterOperator/Security.js:89:17)
>    at DBClient.init (/app/ClusterOperator/DBClient.js:80:28)
R    at async Object.exports.createClient (/app/ClusterOperator/DBClient.js:193:5)
O    at async Function.ConnectLocalDB (/app/ClusterOperator/Operator.js:596:24)
F    at async Function.initDB (/app/ClusterOperator/Operator.js:607:9)
D    at async Function.init (/app/ClusterOperator/Operator.js:622:5)
>    at async initServer (/app/ClusterOperator/server.js:69:3)
#Waiting for local DB to boot up...
8Error: Unsupported state or unable to authenticate data
=    at Decipheriv.final (node:internal/crypto/cipher:193:29)
A    at Function.decrypt (/app/ClusterOperator/Security.js:60:57)
@    at Function.getKey (/app/ClusterOperator/Security.js:89:17)
>    at DBClient.init (/app/ClusterOperator/DBClient.js:80:28)
R    at async Object.exports.createClient (/app/ClusterOperator/DBClient.js:193:5)
O    at async Function.ConnectLocalDB (/app/ClusterOperator/Operator.js:596:24)
F    at async Function.initDB (/app/ClusterOperator/Operator.js:607:9)
D    at async Function.init (/app/ClusterOperator/Operator.js:622:5)
>    at async initServer (/app/ClusterOperator/server.js:69:3)
#Waiting for local DB to boot up...

```

**Comment by alihm** [comment]
This should be fixed now.
